Repository felangel/flow_builder, pull requests merged in 2021-11, with the labels that each got.

#72 feat: add parameter names to OnGeneratePages
  lib/flow_builder.dart
Labels: enhancement

#74 fix: removeListener when FlowController is complete
  lib/flow_builder.dart
  test/flow_builder_test.dart
Labels: bug

#75 chore: v0.0.6
  CHANGELOG.md
  pubspec.yaml
Labels: chore
